### ISSUE TITLE
not running after git clone

### ISSUE THREAD

**Issue by reactdevrocks** [iArunava/YOLOv3-Object-Detection-with-OpenCV#2]
gives this error
`Apples-MacBook-Pro:YOLOv3-Object-Detection-with-OpenCV Apple$ python3 yolo.py
Traceback (most recent call last):
  File "yolo.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy''
`

**Comment by iArunava** [comment]
!pip install numpy
